---
method: plum

# Point cloud folder path
pointCloudFolder: ../../../sampleData/point_clouds/
sensorMaxRange: 100
sensorMinRange: -1
subsampleRadius: 0
platformToSensor: [0.0,0.0,0.0,0.0,0.0,0.0]
pcRegionOfInterest: []

# Lookup table parameters
lookupTableFile: ../../../sampleData/lookupTables/StanfordBunny

# Search heuristic performance
searchRotSigma: 0.05 # rad
searchTransSigma: 3 # m
searchNoIterations: 40
searchResampleSize: 1000
searchSeed: [0,0,0.3491,25,15,-10] # (rad,rad,rad,m,m,m)
searchMinDev: [-3.1416,-3.1416,-3.1416,-40,-30,-10] # (rad,rad,rad,m,m,m)
searchMaxDev: [3.1416,3.1416,3.1416,40,30,10] # (rad,rad,rad,m,m,m)
searchStepSizes: [1.5708,1.5708,1.5708,5,5,5] # (rad,rad,rad,m,m,m)